sr: 16000
noisy_test_dataset_dir: /content/gdrive/MyDrive/year2/audio_processing_project_binaural/Dataset/noisy_testset_1f
noisy_training_dataset_dir: /content/gdrive/MyDrive/year2/audio_processing_project_binaural/Dataset/noisy_trainset_1f
noisy_validation_dataset_dir: /content/gdrive/MyDrive/year2/audio_processing_project_binaural/Dataset/noisy_valset_1f
target_test_dataset_dir: /content/gdrive/MyDrive/year2/audio_processing_project_binaural/Dataset/clean_testset_1f
target_training_dataset_dir: /content/gdrive/MyDrive/year2/audio_processing_project_binaural/Dataset/clean_trainset_1f
target_validation_dataset_dir: /content/gdrive/MyDrive/year2/audio_processing_project_binaural/Dataset/clean_valset_1f

